// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwcCS9DhUvZycqrcJ3q-pQdTeBEGXbM8c',
    appId: '1:722236906357:web:d0d43d3216c2de6ecd113c',
    messagingSenderId: '722236906357',
    projectId: 'flow-app-fcd6e',
    authDomain: 'flow-app-fcd6e.firebaseapp.com',
    storageBucket: 'flow-app-fcd6e.firebasestorage.app',
    measurementId: 'G-NX164Z375D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAxQCwtTrPSDY3jVS-XhzUjgvsMn8eYMO0',
    appId: '1:722236906357:android:4de5a50e36c117f6cd113c',
    messagingSenderId: '722236906357',
    projectId: 'flow-app-fcd6e',
    storageBucket: 'flow-app-fcd6e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmwflh8DCJMUST5RzQ2p9lTir_U98BxKI',
    appId: '1:722236906357:ios:42829acad109505fcd113c',
    messagingSenderId: '722236906357',
    projectId: 'flow-app-fcd6e',
    storageBucket: 'flow-app-fcd6e.firebasestorage.app',
    iosBundleId: 'com.example.flutterFlowApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmwflh8DCJMUST5RzQ2p9lTir_U98BxKI',
    appId: '1:722236906357:ios:42829acad109505fcd113c',
    messagingSenderId: '722236906357',
    projectId: 'flow-app-fcd6e',
    storageBucket: 'flow-app-fcd6e.firebasestorage.app',
    iosBundleId: 'com.example.flutterFlowApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwcCS9DhUvZycqrcJ3q-pQdTeBEGXbM8c',
    appId: '1:722236906357:web:3d5413a756206b57cd113c',
    messagingSenderId: '722236906357',
    projectId: 'flow-app-fcd6e',
    authDomain: 'flow-app-fcd6e.firebaseapp.com',
    storageBucket: 'flow-app-fcd6e.firebasestorage.app',
    measurementId: 'G-K6LG1ZPGPD',
  );
}
